apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  selector:
    matchLabels:
      app: postgres-pod
  template:
    metadata:
      labels:
        app: postgres-pod
    spec:
      containers:
        - name: postgres
          image: postgres:15.3
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD_FILE
              value: /etc/secrets/postgres-password
          volumeMounts:
            - name: postgres-secret-volume
              mountPath: /etc/secrets
              readOnly: true
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-secret-volume
          secret:
            secretName: postgres-secret
            defaultMode: 0400
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-pvc