apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-kube-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-kube-2
  template:
    metadata:
      labels:
        app: hello-kube-2
    spec:
      containers:
        - name: web
          image: aaghamohammadi/hello_kube:1.0.0
